trigger:
- master

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: jenkins-extension

stages:
  - stage: Run_and_publish_unit_tests
    jobs:
      - job:
        steps:
          - task: TfxInstaller@3
            inputs:
              version: "v0.7.x"
          - task: Npm@1
            displayName: Install dependencies
            inputs:
              command: 'install'
              workingDir: 'triggerJenkinsJobTask'
          - task: Bash@3
            displayName: Compile Javascript and install mocha package
            inputs:
              targetType: "inline"
              script: |
                cd triggerJenkinsJobTask
                tsc
                npm install mocha --save-dev
          - task: Npm@1
            displayName: Run unit tests
            inputs:
              command: 'custom'
              workingDir: 'triggerJenkinsJobTask'
              customCommand: 'test'
            env:
              JOB_AUTHENTICATION_TOKEN: '$(jobAuthenticationToken)'
              JENKINS_API_TOKEN: '$(jenkinsApiToken)'
              JENKINS_USERNAME: 'test'
              JENKINS_URL: 'https://jenkins.iktech.io/job/test'
              JENKINS_URL_2: 'https://jenkins.iktech.io/job/test-2'
              JENKINS_URL_PARAM: 'https://jenkins.iktech.io/job/test-param'
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/test-result.xml'
  - stage: Package_extension_and_publish_build_artifacts
    jobs:
      - job:
        steps:
          - task: TfxInstaller@3
            inputs:
              version: "v0.7.x"
          - task: Npm@1
            displayName: Install dependencies
            inputs:
              command: 'install'
              workingDir: 'triggerJenkinsJobTask'
          - task: Bash@3
            displayName: Compile Javascript
            inputs:
              targetType: "inline"
              script: |
                cd triggerJenkinsJobTask
                tsc
          - task: QueryAzureDevOpsExtensionVersion@3
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'marketplace'
              publisherId: '$(PublisherID)'
              extensionId: '$(ExtensionID)'
              versionAction: 'Patch'
              outputVariable: 'Task.Extension.Version'
          - task: PackageAzureDevOpsExtension@3
            inputs:
              rootFolder: '$(System.DefaultWorkingDirectory)'
              publisherId: '$(PublisherID)'
              extensionId: '$(ExtensionID)'
              artifactName: '$(ExtensionName)'
              extensionVersion: '$(Task.Extension.Version)'
              updateTasksVersion: true
              updateTasksVersionType: 'patch'
              extensionVisibility: 'private' # Change to public if you're publishing to the marketplace
              extensionPricing: 'free'
          - task: CopyFiles@2
            displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)"
            inputs:
              Contents: "**/*.vsix"
              TargetFolder: "$(Build.ArtifactStagingDirectory)"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(ArtifactName)'
              publishLocation: 'Container'
  - stage: Download_build_artifacts_and_publish_the_extension
    jobs:
      - job:
        steps:
          - task: TfxInstaller@3
            inputs:
              version: "v0.7.x"
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "$(ArtifactName)"
              downloadPath: "$(System.DefaultWorkingDirectory)"
          - task: PublishAzureDevOpsExtension@3
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'marketplace'
              fileType: 'vsix'
              vsixFile: '$(ArtifactName)/$(PublisherID).*.vsix'
              publisherId: '$(PublisherID)'
              extensionId: '$(ExtensionID)'
              extensionName: '$(ExtensionName)'
              updateTasksVersion: false
              extensionVisibility: 'public' # Change to public if you're publishing to the marketplace
              extensionPricing: 'free'
